// Highly Divisible Triangular Number
// The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 +2 +3 +4 +5 +6 +7 =28. The first ten terms would be:
// 1,3,6,10,15,21,28,36,45,55,…

// Let us list the factors of the first seven triangle numbers:

// 𝟏	:1
// 𝟑	:1,3
// 𝟔	:1,2,3,6
// 𝟏𝟎	:1,2,5,10
// 𝟏𝟓	:1,3,5,15
// 𝟐𝟏	:1,3,7,21
// 𝟐𝟖	:1,2,4,7,14,28

// We can see that 28 is the first triangle number to have over five divisors.

// What is the value of the first triangle number to have over five hundred divisors?

const noOfFactors = (num) => {
  const factors = [];
  const sqrtNum = Math.sqrt(num);
  for (let i = 1; i <= sqrtNum; i++) {
    if (num % i === 0) factors.push(i, num / i);
  }
  // console.log(factors);
  return factors.length;
};

const highlyDivisibleTriangularNumber = (limit) => {
  let currentTriangleNumber = 0;
  let i = 1;
  let factors = noOfFactors(currentTriangleNumber);
  while (factors < limit) {
    currentTriangleNumber += i;
    i++;
    factors = noOfFactors(currentTriangleNumber);
  }
  return currentTriangleNumber;
};

highlyDivisibleTriangularNumber(500)
