// Even Fibinocci Numbers
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1,2,3,5,8,13,21,34,55,89,…
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

const sumOfEvenValuedTermsInFibbSeq = (limit) => {
  let currentTerm = 1;
  let nextTerm = 2;
  let fibbonaciTerm = currentTerm + nextTerm;
  let sum = 2;
  while (fibbonaciTerm < limit) {
    sum += fibbonaciTerm % 2 === 0 ? fibbonaciTerm : 0;
    currentTerm = nextTerm;
    nextTerm = fibbonaciTerm;
    fibbonaciTerm = currentTerm + nextTerm;
  }
  return sum;
}

sumOfEvenValuedTermsInFibbSeq(4000000)